valid = [
  { atom = "_/_", eapis = "0-", category = "_", package = "_" },
  { atom = "_/_-", eapis = "0-", category = "_", package = "_-" },
  { atom = "_.+-/_+-", eapis = "0-", category = "_.+-", package = "_+-" },
  { atom = "_--/_--", eapis = "0-", category = "_--", package = "_--" },
  { atom = "a/b", eapis = "0-", category = "a", package = "b" },
  { atom = "a/b-", eapis = "0-", category = "a", package = "b-" },
  { atom = "a/b-r100", eapis = "0-", category = "a", package = "b-r100" },
  { atom = "<a/b-r0-1-r2", eapis = "0-", category = "a", package = "b-r0", version = "<1-r2" },
  { atom = "<=a/b-1", eapis = "0-", category = "a", package = "b", version = "<=1" },
  { atom = "=a/b-1-r1", eapis = "0-", category = "a", package = "b", version = "=1-r1" },
  { atom = "=a/b-3*", eapis = "0-", category = "a", package = "b", version = "=3*" },
  { atom = "=a/b-3-r1*", eapis = "0-", category = "a", package = "b", version = "=3-r1*" },
  { atom = "~a/b-0", eapis = "0-", category = "a", package = "b", version = "~0" },
  { atom = ">=a/b-2", eapis = "0-", category = "a", package = "b", version = ">=2" },
  { atom = ">a/b-3-r0", eapis = "0-", category = "a", package = "b", version = ">3-r0" },
  { atom = ">a/b-3-c-4-r3", eapis = "0-", category = "a", package = "b-3-c", version = ">4-r3" },
  ## EAPI specific validity
  # slot deps in EAPI >= 1
  { atom = "a/b:0", eapis = "1-", category = "a", package = "b", slot = "0" },
  # blockers in EAPI >= 2
  { atom = "!a/b", eapis = "2-", category = "a", package = "b" },
  { atom = "!!a/b", eapis = "2-", category = "a", package = "b" },
  # use deps in EAPI >= 2
  { atom = "a/b[use]", eapis = "2-", category = "a", package = "b" },
  { atom = "a/b[a,b=,!c=,d?,!e?,-f]", eapis = "2-", category = "a", package = "b" },
  # use dep defaults in EAPI >= 4
  { atom = "a/b[use(+)]", eapis = "4-", category = "a", package = "b" },
  { atom = "a/b[use(-)]", eapis = "4-", category = "a", package = "b" },
  { atom = "a/b[a(-),b(+)=,!c(-)=,d(+)?,!e(-)?,-f(+)]", eapis = "4-", category = "a", package = "b" },
  # subslot deps in EAPI >= 5
  { atom = "a/b:0/1", eapis = "5-", category = "a", package = "b", slot = "0", subslot = "1" },
  # slot operators in EAPI >= 5
  { atom = "a/b:*", eapis = "5-", category = "a", package = "b", slot_op = "*" },
  { atom = "a/b:=", eapis = "5-", category = "a", package = "b", slot_op = "=" },
  { atom = "a/b:0=", eapis = "5-", category = "a", package = "b", slot = "0", slot_op = "=" },
]

# invalid atoms
# format: [invalid atom, invalidity EAPI range]
invalid = [
  ["", "0-"],
  ["a", "0-"],
  ["/b", "0-"],
  ["a/+b", "0-"],
  [".a/.b", "0-"],
  # invalid version suffixes
  ["=a/b-1_a", "0-"],
  ["=a/b-1_a1", "0-"],
  # invalid slot deps
  ["a/b:", "0-"],
  ["a/b:+", "0-"],
  ["a/b:+0", "0-"],
  ["a/b:.a", "0-"],
  ["a/b:-b", "0-"],
  ["a/b:a@b", "0-"],
  ["a/b:0/1", "0-4"],
  # invalid blockers
  ["!!!a/b", "0-"],
  ["!a/b-0", "0-"],
  ["!!a/b-0-r1", "0-"],
  # invalid use deps
  ["a/b[]", "0-"],
  ["a/b[-]", "0-"],
  ["a/b[-a?]", "0-"],
  ["a/b[!a]", "0-"],
  # invalid use dep defaults
  ["a/b[(-)]", "0-"],
  ["a/b[(+)]", "0-"],
  ["a/b[a()]", "0-"],
  ["a/b[a(?)]", "0-"],
  ["a/b[a(b)]", "0-"],
  ["a/b[a(-+)]", "0-"],
  ["a/b[a(++)]", "0-"],
  ["a/b[a((+))]", "0-"],
  ["a/b[a(-)b]", "0-"],
  # invalid subslot deps
  ["a/b:/", "0-"],
  ["a/b:/0", "0-"],
  ["a/b:0/", "0-"],
  ["a/b:0/+1", "0-"],
  ["a/b:0//1", "0-"],
  ["a/b:0/1/2", "0-"],
  # invalid slot ops
  ["a/b:*0", "0-"],
  ["a/b:=0", "0-"],
  ["a/b:*=", "0-"],
  ["a/b:==", "0-"],
  # package names can't end in a hyphen followed by anything matching a version
  ["a/b-0", "0-"],
  ["<a/b-1-1", "0-"],
  ["=a/b-1-c-2-3", "0-"],
  [">a/b-1-r2-3-r4", "0-"],
  # version operator with missing version
  ["~a/b", "0-"],
  ["~a/b-r1", "0-"],
  [">a/b", "0-"],
  [">=a/b-r1", "0-"],
  # '~' operator can't be used with a revision
  ["~a/b-1-r1", "0-"],
  # '*' suffix can only be used for versioned atoms with the '=' operator
  [">=a/b-0*", "0-"],
  ["~a/b-0*", "0-"],
  ["a/b-0*", "0-"],
  ["a/b*", "0-"],
  # '*' suffix can only be used with valid version strings
  ["=a/b-0.*", "0-"],
  ["=a/b-0-r*", "0-"],
  # repo deps in no official EAPI
  ['cat/pkg::repo', '0~'],
  # invalid repo deps
  ["a/b::", "0-"],
  ["a/b::-repo", "0-"],
  ["a/b::repo-1", "0-"],
  ["a/b::repo@path", "0-"],
]

# atom sorting
# format: [unsorted, sorted]
sorting = [
  # categories
  [["c/pkg", "b/pkg", "a/pkg"], ["a/pkg", "b/pkg", "c/pkg"]],
  # packages
  [["cat/c", "cat/b", "cat/a"], ["cat/a", "cat/b", "cat/c"]],
  # blocks
  [["!a/b", "!!a/b", "a/b"], ["a/b", "!!a/b", "!a/b"]],
  # version ops
  [
      [">a/b-1", ">=a/b-1", "~a/b-1", "=a/b-1*", "=a/b-1", "<=a/b-1", "<a/b-1"],
      ["<a/b-1", "<=a/b-1", "=a/b-1", "=a/b-1*", "~a/b-1", ">=a/b-1", ">a/b-1"]
  ],
  # slots
  [["a/b:2", "a/b:1", "a/b:0"], ["a/b:0", "a/b:1", "a/b:2"]],
  # subslots
  [["a/b:0/2", "a/b:0/1", "a/b:0/0"], ["a/b:0/0", "a/b:0/1", "a/b:0/2"]],
  # use deps
  [["a/b[c]", "a/b[b]", "a/b[a]"], ["a/b[a]", "a/b[b]", "a/b[c]"]],
  # equal versions shouldn't be sorted
  [["=a/b-0", "=a/b-00", "=a/b-0-r0"], ["=a/b-0", "=a/b-00", "=a/b-0-r0"]],
  [["=a/b-1.0.2", "=a/b-1.0.2-r0", "=a/b-1.000.2"], ["=a/b-1.0.2", "=a/b-1.0.2-r0", "=a/b-1.000.2"]],
  # simple versions
  [["=a/b-2", "=a/b-1", "=a/b-0"], ["=a/b-0", "=a/b-1", "=a/b-2"]],
  [["=a/b-1.100", "=a/b-1.10", "=a/b-1.1"], ["=a/b-1.1", "=a/b-1.10", "=a/b-1.100"]],
  # letter suffixes
  [["=a/b-1z", "=a/b-1y", "=a/b-1b", "=a/b-1a"], ["=a/b-1a", "=a/b-1b", "=a/b-1y", "=a/b-1z"]],
  # release suffixes
  [
      ["=a/b-1_p", "=a/b-1_rc", "=a/b-1_pre", "=a/b-1_beta", "=a/b-1_alpha"],
      ["=a/b-1_alpha", "=a/b-1_beta", "=a/b-1_pre", "=a/b-1_rc", "=a/b-1_p"]
  ],
  [["=a/b-1_p2", "=a/b-1_p1", "=a/b-1_p0"], ["=a/b-1_p0", "=a/b-1_p1", "=a/b-1_p2"]],
  # revisions
  [["=a/b-1-r2", "=a/b-1-r1", "=a/b-1-r0"], ["=a/b-1-r0", "=a/b-1-r1", "=a/b-1-r2"]],
]
